# SPDX-FileCopyrightText: 2026-present Inria
#
# SPDX-License-Identifier: BSD-3-Clause

"""Mari's fixed TSCH schedules and slot timing, sourced from the firmware.

Every mari device compiles the same four schedule tables in
(`firmware/mari/all_schedules.c`): fixed, ordered sequences of cell types
(`B` beacon, `U` dedicated uplink, `S` shared/contention uplink, `D`
downlink). A schedule is fully described by that ordered sequence plus its
node capacity, and the whole-slot duration comes from `firmware/mari/mac.h`.

Mirrors the approach in ``mari-evaluation/simulations/multigw``: parse the
firmware source rather than transcribe its constants by hand, so this module
can't silently drift from what the firmware actually ships. Unlike multigw
this package must also work from a standalone `pydotbot` install with no
sibling mari checkout, so a generated JSON snapshot
(`mari_schedules_generated.json`, produced by
`utils/generate_mari_schedules.py`) is the fallback when no firmware source
can be found.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

#: Env var pointing at a mari checkout (repo root, `firmware/`, or `firmware/mari/`).
MARI_DIR_ENV = "MARI_FIRMWARE_DIR"

_REQUIRED_FILES = ("all_schedules.c", "mac.h", "models.h")
_SUFFIXES = (Path("."), Path("mari"), Path("firmware") / "mari")

#: Bundled fallback, regenerated by `utils/generate_mari_schedules.py`.
GENERATED_SNAPSHOT = Path(__file__).with_name("mari_schedules_generated.json")

#: Cell types, from `slot_type_t` in `models.h`.
BEACON = "B"
SHARED_UPLINK = "S"
DOWNLINK = "D"
UPLINK = "U"
CELL_TYPES = (BEACON, SHARED_UPLINK, DOWNLINK, UPLINK)


class MariSourcesNotFound(RuntimeError):
    """Raised when the mari firmware checkout cannot be located."""


class ScheduleParseError(RuntimeError):
    """Raised when `all_schedules.c` does not look the way this parser expects."""


class FirmwareParseError(RuntimeError):
    """Raised when `mac.h` does not look the way the macro evaluator expects."""


@dataclass(frozen=True)
class MariSchedule:
    """One fixed mari schedule, as compiled into every device."""

    name: str
    id: int
    max_nodes: int
    cell_types: tuple[str, ...]
    slot_duration_ms: float

    @property
    def n_cells(self) -> int:
        return len(self.cell_types)

    @property
    def slotframe_ms(self) -> float:
        return self.n_cells * self.slot_duration_ms

    def uplink_cell_indices(self) -> tuple[int, ...]:
        return tuple(i for i, t in enumerate(self.cell_types) if t == UPLINK)

    def downlink_cell_indices(self) -> tuple[int, ...]:
        return tuple(i for i, t in enumerate(self.cell_types) if t == DOWNLINK)


# ---------------------------------------------------------------- sources --
# Resolution + comment-stripping, mirrored from
# mari-evaluation/simulations/multigw/sources.py.


def _is_mari_dir(path: Path) -> bool:
    return all((path / name).is_file() for name in _REQUIRED_FILES)


def _normalise(base: Path) -> Path | None:
    for suffix in _SUFFIXES:
        candidate = base / suffix
        if _is_mari_dir(candidate):
            return candidate
    return None


def _not_found(tried: list[Path], hint: str) -> MariSourcesNotFound:
    return MariSourcesNotFound(
        "could not find the mari firmware sources (expected "
        + ", ".join(_REQUIRED_FILES)
        + " in one directory).\nSearched: "
        + "\n          ".join(str(path) for path in tried)
        + "\n"
        + hint
    )


def resolve_mari_dir(explicit: str | os.PathLike[str] | None = None) -> Path:
    """Return the directory holding the mari firmware sources.

    Resolution order: an explicit path, then `$MARI_FIRMWARE_DIR`, then a
    sibling `mari` checkout found by walking up from this file (the usual
    side-by-side workspace layout: `repos/PyDotBot/` next to `repos/mari/`).
    An explicit path or env var that does not hold the sources is an error
    rather than a reason to keep looking.
    """
    for base, origin in (
        (explicit, "the path given"),
        (os.environ.get(MARI_DIR_ENV) or None, f"${MARI_DIR_ENV}"),
    ):
        if base is None:
            continue
        path = Path(base).expanduser()
        found = _normalise(path)
        if found is None:
            raise _not_found([path], f"{origin} does not hold the mari firmware sources.")
        return found.resolve()

    tried = [ancestor / "mari" for ancestor in Path(__file__).resolve().parents]
    for base in tried:
        found = _normalise(base)
        if found is not None:
            return found.resolve()
    raise _not_found(
        tried,
        f"Set {MARI_DIR_ENV} or pass mari_dir= with the path to the mari checkout.",
    )


_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
_LINE_COMMENT = re.compile(r"//[^\n]*")


def _strip_comments(text: str) -> str:
    def _blank_block(match: re.Match[str]) -> str:
        return "\n" * match.group(0).count("\n")

    return _LINE_COMMENT.sub("", _BLOCK_COMMENT.sub(_blank_block, text))


def _read_source(name: str, mari_dir: str | os.PathLike[str] | None = None) -> str:
    return _strip_comments((resolve_mari_dir(mari_dir) / name).read_text(encoding="utf-8"))


# -------------------------------------------------------------- schedules --
# Parses `schedule_t schedule_<name> = { ... };` designated initialisers, as
# multigw's schedules.py does. Only the cell TYPE is kept - channel offset,
# assigned_node_id and the rest of `cell_t` are per-run state this simulator
# doesn't need.

_SCHEDULE_RE = re.compile(
    r"schedule_t\s+schedule_(?P<name>\w+)\s*=\s*\{(?P<body>.*?)\n\}\s*;",
    re.DOTALL,
)
_FIELD_RE = re.compile(r"\.(?P<key>\w+)\s*=\s*(?P<value>0[xX][0-9a-fA-F]+|\d+)")
_CELL_TYPE_RE = re.compile(r"\{\s*'(?P<type>[A-Z])'\s*,")


def _parse_schedule_cells(text: str) -> dict[str, tuple[int, int, tuple[str, ...]]]:
    """Parse every `schedule_t` definition; returns name -> (id, max_nodes, cell_types)."""
    parsed: dict[str, tuple[int, int, tuple[str, ...]]] = {}
    for match in _SCHEDULE_RE.finditer(text):
        name = match.group("name")
        body = match.group("body")
        fields = {m.group("key"): int(m.group("value"), 0) for m in _FIELD_RE.finditer(body)}
        cell_types = tuple(m.group("type") for m in _CELL_TYPE_RE.finditer(body))
        missing = {"id", "max_nodes", "n_cells"} - fields.keys()
        if missing:
            raise ScheduleParseError(f"schedule_{name}: missing field(s) {sorted(missing)}")
        if len(cell_types) != fields["n_cells"]:
            raise ScheduleParseError(
                f"schedule_{name}: .n_cells says {fields['n_cells']} "
                f"but {len(cell_types)} cell initialisers were found"
            )
        bad = sorted(set(cell_types) - set(CELL_TYPES))
        if bad:
            raise ScheduleParseError(f"schedule_{name}: unknown cell type(s) {bad}")
        parsed[name] = (fields["id"], fields["max_nodes"], cell_types)
    if not parsed:
        raise ScheduleParseError("no schedule_t definitions found")
    return parsed


# ------------------------------------------------------------------ timing --
# Evaluates the handful of `#define`s in mac.h that determine
# MARI_WHOLE_SLOT_DURATION, the way the C preprocessor would, rather than
# copying the computed constant. Scoped to macro arithmetic only (mac.h needs
# no enum/struct sizing) - a reduced version of multigw's timing.py.

_DEFINE_RE = re.compile(r"^[ \t]*#[ \t]*define[ \t]+([A-Za-z_]\w*)(?:[ \t]+(.*))?$", re.MULTILINE)
_IDENT_RE = re.compile(r"[A-Za-z_]\w*")
_ARITHMETIC_RE = re.compile(r"[0-9+\-*/%()\s]+")

#: Preprocessor symbols mac.h relies on from outside itself.
_BUILTIN_MACROS = {"UINT8_MAX": 255}


class _MacroModel:
    def __init__(self, text: str) -> None:
        self._defines: dict[str, str] = {}
        for match in _DEFINE_RE.finditer(text):
            name, value = match.group(1), (match.group(2) or "").strip()
            self._defines.setdefault(name, value)
        self._cache: dict[str, int] = {}

    def macro(self, name: str) -> int:
        if name in self._cache:
            return self._cache[name]
        if name in _BUILTIN_MACROS:
            return _BUILTIN_MACROS[name]
        if name not in self._defines:
            raise FirmwareParseError(f"unknown macro {name}")
        expression = self._defines[name]
        if not expression:
            raise FirmwareParseError(f"macro {name} has no value (it is a flag)")
        value = self._evaluate(expression, (name,))
        self._cache[name] = value
        return value

    def _evaluate(self, expression: str, stack: tuple[str, ...]) -> int:
        def substitute(match: re.Match[str]) -> str:
            name = match.group(0)
            if name in stack:
                raise FirmwareParseError(f"macro {name} expands to itself")
            if name in _BUILTIN_MACROS:
                return f"({_BUILTIN_MACROS[name]})"
            if name in self._defines:
                return f"({self._evaluate(self._defines[name], stack + (name,))})"
            raise FirmwareParseError(f"unknown symbol {name!r} in expression {expression!r}")

        expression = _IDENT_RE.sub(substitute, expression)
        if not _ARITHMETIC_RE.fullmatch(expression):
            raise FirmwareParseError(f"expression is not plain integer arithmetic: {expression!r}")
        # C integer division truncates; every value here is positive, so floor
        # division agrees with it.
        return int(eval(re.sub(r"/(?!/)", "//", expression), {"__builtins__": {}}, {}))


def _slot_duration_ms(mari_dir: str | os.PathLike[str] | None = None) -> float:
    model = _MacroModel(_read_source("mac.h", mari_dir))
    return model.macro("MARI_WHOLE_SLOT_DURATION") / 1000.0


# ------------------------------------------------------------------- load --


def _load_from_firmware(mari_dir: str | os.PathLike[str] | None = None) -> dict[str, MariSchedule]:
    raw = _parse_schedule_cells(_read_source("all_schedules.c", mari_dir))
    slot_ms = _slot_duration_ms(mari_dir)
    return {
        name: MariSchedule(
            name=name, id=id_, max_nodes=max_nodes, cell_types=cell_types, slot_duration_ms=slot_ms
        )
        for name, (id_, max_nodes, cell_types) in raw.items()
    }


def _load_generated() -> dict[str, MariSchedule]:
    data = json.loads(GENERATED_SNAPSHOT.read_text(encoding="utf-8"))
    slot_ms = data["slot_duration_ms"]
    return {
        name: MariSchedule(
            name=name,
            id=entry["id"],
            max_nodes=entry["max_nodes"],
            cell_types=tuple(entry["cell_types"]),
            slot_duration_ms=slot_ms,
        )
        for name, entry in data["schedules"].items()
    }


@lru_cache(maxsize=None)
def _load_cached(mari_dir_key: str | None, explicit: bool) -> tuple[tuple[str, MariSchedule], ...]:
    if explicit or os.environ.get(MARI_DIR_ENV):
        # An explicit ask that fails to resolve should be loud, not a silent
        # fallback to a possibly-stale bundled snapshot.
        schedules = _load_from_firmware(mari_dir_key)
    else:
        try:
            schedules = _load_from_firmware(None)
        except MariSourcesNotFound:
            schedules = _load_generated()
    return tuple(schedules.items())


def load_schedules(mari_dir: str | os.PathLike[str] | None = None) -> dict[str, MariSchedule]:
    """Load the four mari schedules, by firmware name (`tiny`/`medium`/`big`/`huge`).

    Tries a mari firmware checkout first (explicit `mari_dir`, then
    `$MARI_FIRMWARE_DIR`, then a sibling `mari/` directory); falls back to the
    bundled generated snapshot only when no checkout was found and none was
    explicitly asked for.
    """
    key = None if mari_dir is None else str(mari_dir)
    return dict(_load_cached(key, mari_dir is not None))


def select_schedule(n_bots: int, mari_dir: str | os.PathLike[str] | None = None) -> MariSchedule:
    """The smallest mari schedule whose capacity covers `n_bots` nodes."""
    schedules = load_schedules(mari_dir)
    candidates = sorted(schedules.values(), key=lambda s: s.max_nodes)
    for schedule in candidates:
        if n_bots <= schedule.max_nodes:
            return schedule
    largest = candidates[-1].max_nodes if candidates else 0
    raise ValueError(f"no mari schedule supports {n_bots} nodes (largest is {largest})")
